version: "3.7"
services:
 db:
   image: "mysql:5.7"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
   ports:
      - "3306:3306"
 redis:
   image: "redis:4.0-alpine"
   command: redis-server
   volumes:
      - "redis:/data"
 elasticsearch:
   image: "docker.elastic.co/elasticsearch/elasticsearch:7.10.2"
   hostname: elasticsearch
   environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
   ports:
      - "9200:9200"

 website:
   depends_on:
      - "db"
      - "redis"
   build: .
   command: bundle exec rails server -b 0.0.0.0 -p 3000
   ports:
      - "3000:3000"
   environment:
     DB_USERNAME: root
     DB_PASSWORD: root
     DB_DATABASE: sample
     DB_PORT: 3306
     DB_HOST: db
   #   RAILS_ENV: production
     RAILS_MAX_THREADS: 5
   volumes:
      - ".:/app"

 sidekiq:
   depends_on:
      - "db"
      - "redis"
      - "website"
   build: .
   command: bundle exec sidekiq
   volumes:
      - ".:/app"
   environment:
     REDIS_URL: redis://redis:6379/0

volumes:
 redis:
 db: